CONVERT_TO=rp2040_ce
UNICODE_COMMON = yes
TRI_LAYER_ENABLE = yes
MOUSEKEY_ENABLE = yes
ONESHOT_ENABLE = yes
# # UNICODEMAP_ENABLE = yes
# UCIS_ENABLE = yes
# UNICODE_ENABLE = false

SPLIT_KEYBOARD = yes

