CONVERT_TO=rp2040_ce
AUTO_SHIFT_ENABLE = yes
UNICODE_COMMON = yes
TRI_LAYER_ENABLE = yes
KEY_OVERRIDE_ENABLE = yes
MOUSEKEY_ENABLE = yes
COMBO_ENABLE = yes
ONESHOT_ENABLE = yes
# # UNICODEMAP_ENABLE = yes
# UCIS_ENABLE = yes
# UNICODE_ENABLE = false

# MCU = atmega32u4
# BOOTLOADER = caterina
